config/routes.rb
Rails.application.routes.draw do
  resources :contacts do
    delete 'destroy_all', on: :collection
  end

  root 'contacts#index'
end

app/models/contact.rb
class Contact < ActiveRecord::Base

  validates :first_name, presence: true
  validates :last_name, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :set_contact, only: [:show, :edit, :update, :destroy]

  # GET /contacts
  # GET /contacts.json
  def index
    @contacts = Contact.all
  end

  # GET /contacts/1
  # GET /contacts/1.json
  def show
  end

  # GET /contacts/new
  def new
    @contact = Contact.new
  end

  # GET /contacts/1/edit
  def edit
  end

  # POST /contacts
  # POST /contacts.json
  def create
    @contact = Contact.new(contact_params)

    respond_to do |format|
      if @contact.save
        format.html { redirect_to @contact, notice: 'Contact was successfully created.' }
        format.json { render :show, status: :created, location: @contact }
      else
        format.html { render :new }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contacts/1
  # PATCH/PUT /contacts/1.json
  def update
    respond_to do |format|
      if @contact.update(contact_params)
        format.html { redirect_to @contact, notice: 'Contact was successfully updated.' }
        format.json { render :show, status: :ok, location: @contact }
      else
        format.html { render :edit }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contacts/1
  # DELETE /contacts/1.json
  def destroy
    @contact.destroy
    respond_to do |format|
      format.html { redirect_to contacts_url, notice: 'Contact record was successfully deleted.' }
      format.json { head :no_content }
    end
  end

 def destroy_all
    Contact.destroy_all
    respond_to do |format|
      format.html { redirect_to contacts_url, notice: 'All contact records were successfully deleted.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contact
      @contact = Contact.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def contact_params
      params.require(:contact).permit(:first_name, :last_name, :phone, :email)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/views/contacts/_form.html.erb
<%= form_for(@contact) do |f| %>
  <% if @contact.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@contact.errors.count, "error") %> prohibited this contact from being saved:</h2>

      <ul>
      <% @contact.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :phone %><br>
    <%= f.text_field :phone %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/contacts/edit.html.erb
<h1>Editing Contact</h1>

<%= render 'form' %>

<%= button_to 'Show', contact_path(@contact), method: :get, class: "btn btn-xs btn-default", form_class: "inline-button" %>
<%= button_to 'Back', :back, method: :get, class: "btn btn-xs btn-default", form_class: "inline-button" %>

app/views/contacts/index.html.erb
<h3>Contacts</h3>
<hr>

<form class="form-inline" role="form">

<div class="container">

<table  class="table table-striped">
  <thead>
    <tr>
      <th class="col-id">ID</th>
      <th class="col-medium">First name</th>
      <th class="col-medium">Last name</th>
      <th class="col-medium">Phone</th>
      <th>Email</th>
      <th class="col-wide">Created At</th>
      <th class="col-wide">Actions</th>
     </tr>
  </thead>

  <tbody>
    <% @contacts.each do |contact| %>
      <tr>
        <td><%= contact.id %></td>
        <td><%= contact.first_name %></td>
        <td><%= contact.last_name %></td>
        <td><%= contact.phone %></td>
        <td><%= contact.email %></td>
        <td><%= contact.created_at %></td>
        <td class="container">
          <%= link_to 'Show', contact_path(contact), method: :get, class: "btn btn-xs btn-default" %>
          <%= link_to 'Edit', edit_contact_path(contact), method: :get, class: "btn btn-xs btn-default" %>
          <%# Note: The delete confirmation is presented twice on the first delete in a new
              development session for unknown reasons %>
          <%= link_to 'Delete', contact, method: :delete, class: "btn btn-xs btn-danger", data: { confirm: 'Are you sure you want to destroy this contact record?' } %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
<br>

<div class="container">
  <%= link_to 'New', new_contact_path, method: :get, class: "btn btn-md btn-primary" %>
  <%= link_to 'Delete All', destroy_all_contacts_path, method: :delete, class: "btn btn-md btn-danger", data: { confirm: 'You are about to delete ALL contact records. Are you sure you want to do this?'  } %>
</div>

</form>

app/views/contacts/new.html.erb
<h1>New Contact</h1>

<%= render 'form' %>

<%= button_to 'Back', contacts_path, method: :get, class: "btn btn-xs btn-default", form_class: "inline-button" %>

app/views/contacts/show.html.erb
<p>
  <strong>First name:</strong>
  <%= @contact.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @contact.last_name %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @contact.phone %>
</p>

<p>
  <strong>Email:</strong>
  <%= @contact.email %>
</p>

<%= button_to 'Edit', edit_contact_path(@contact), method: :get, class: "btn btn-xs btn-default", form_class: "inline-button" %>
<%# This Back button should always return to the index page to avoid circular 'back's: %>
<%= button_to 'Back', contacts_path, method: :get, class: "btn btn-xs btn-default", form_class: "inline-button" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Contacts</title>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

  <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
  <%= javascript_include_tag 'https://js.stripe.com/v2/' %>

  <%= csrf_meta_tags %>
  <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
  <!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
  <![endif]-->
</head>
<body>

<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="http://edwinmeyer.com/">Edwin Meyer</a>
    </div>
    <div>
      <ul class="nav navbar-nav">
        <li class="active"><a href="<%= contacts_path %>">Contacts</a></li>
      </ul>
    </div>
  </div>
</nav>

<div class="row" style="padding-left: 3%">

<% if notice %>
    <p id="notice"><%= notice %></p>
<% end %>
<% if alert %>
    <p id="alert"><%= alert %></p>
<% end %>


<%= yield %>

</div>

</body>
</html>